package com.pathfoss.vivoxia.nutrition;

import android.content.Intent;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.DialogFragment;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.pathfoss.vivoxia.R;
import com.pathfoss.vivoxia.general.DownloadService;
import com.pathfoss.vivoxia.general.ReusableMethods;

import java.util.Objects;

@JsonIgnoreProperties(ignoreUnknown = true)
public class FoodImporter extends DialogFragment {

    private final String baseURL = "https://raw.githubusercontent.com/PathFOSS/FoodData/main/food_by_category/";
    private final String[] files = {"alcohol.json",
            "alcoholic_beverages.json",
            "all_noodles.json",
            "antioxidant_supplements.json",
            "antipasto.json",
            "aquatic_invertebrates_or_fish_or_shellfish_or_seafood_combination.json",
            "baby_or_infant_foods_or_beverages.json",
            "baby_or_infant_–_foods_or_beverages.json",
            "bacon.json",
            "bacon_sausages_&_ribs.json",
            "baking.json",
            "baking_accessories.json",
            "baking_additives_&_extracts.json",
            "baking_decorations_&_dessert_toppings.json",
            "baking_needs.json",
            "baking_or_cooking_mixes_frozen.json",
            "baking_or_cooking_mixes_or_supplies.json",
            "baking_or_cooking_mixes_perishable.json",
            "baking_or_cooking_mixes_shelf_stable.json",
            "baking_or_cooking_supplies_shelf_stable.json",
            "beef_prepared_or_processed.json",
            "beer.json",
            "biscuits_chocolate.json",
            "biscuits_cracker.json",
            "biscuits_kids.json",
            "biscuits_or_cookies.json",
            "biscuits_or_cookies_frozen.json",
            "biscuits_or_cookies_shelf_stable.json",
            "biscuits_plain_or_sweet.json",
            "bread.json",
            "bread_&_muffin_mixes.json",
            "bread_frozen.json",
            "bread_incl._buns_and_rolls.json",
            "bread_or_bakery_products_variety_packs.json",
            "bread_shelf_stable.json",
            "breads_&_buns.json",
            "breakfast_cereals_hot_and_cold.json",
            "breakfast_drinks.json",
            "breakfast_foods.json",
            "breakfast_sandwiches_biscuits_&_meals.json",
            "butter_&_spread.json",
            "butter_or_butter_substitutes.json",
            "cake_cookie_&_cupcake_mixes.json",
            "cakes_and_slices.json",
            "cakes_cupcakes_snack_cakes.json",
            "cakes_or_slices_or_biscuits.json",
            "cakes_sweet_frozen.json",
            "cakes_sweet_shelf_stable.json",
            "candy.json",
            "canned_&_bottled_beans.json",
            "canned_condensed_soup.json",
            "canned_fish_and_meat.json",
            "canned_fruit.json",
            "canned_meat.json",
            "canned_or_dried_veges.json",
            "canned_seafood.json",
            "canned_soup.json",
            "canned_tuna.json",
            "canned_vegetables.json",
            "cereal.json",
            "cereal_or_muesli_bars.json",
            "cereal_products_ready_to_eat_perishable.json",
            "cereals_products_not_ready_to_eat_shelf_stable.json",
            "cereals_products_ready_to_eat_shelf_stable.json",
            "cheese.json",
            "cheese_block.json",
            "cheese_or_cheese_substitutes.json",
            "cheese_speciality.json",
            "chewing_gum_&_mints.json",
            "chicken_prepared_or_processed.json",
            "chicken_unprepared_or_unprocessed.json",
            "children's_nutritional_supplements.json",
            "childrens_natural_remedies.json",
            "childrens_nutritional_supplements.json",
            "chili_&_stew.json",
            "chips_or_crisps_or_snack_mixes_natural_or_extruded_shelf_stable.json",
            "chips_pretzels_&_snacks.json",
            "chocolate.json",
            "chocolate_and_chocolate_or_sugar_candy_combinations_confectionery.json",
            "coffee.json",
            "coffee_instant_roast_and_ground.json",
            "coffee_or_tea_or_substitutes.json",
            "condiments_oils_&_dressing.json",
            "confection_&_snacks.json",
            "confectionery.json",
            "confectionery_products.json",
            "cooked_&_prepared.json",
            "cookies_&_biscuits.json",
            "cooking_oils_and_fats.json",
            "crackers_&_biscotti.json",
            "cream.json",
            "cream_or_cream_substitutes.json",
            "croissants_sweet_rolls_muffins_&_other_pastries.json",
            "crusts_&_dough.json",
            "dairy_foods_or_yoghurts.json",
            "dairy_or_egg_based_products_or_meals.json",
            "deli_and_chilled_foods.json",
            "deli_salads.json",
            "desserts_&_custard.json",
            "desserts_frozen.json",
            "desserts_or_dessert_sauces_or_toppings.json",
            "desserts_shelf_stable.json",
            "digestive_&_fiber_supplements.json",
            "dips_&_salsa.json",
            "dips_or_hummus_or_pate.json",
            "dips_shelf_stable.json",
            "doodles_or_puffs.json",
            "dough_based_products_or_meals.json",
            "dough_based_products_or_meals_not_ready_to_eat_savoury_frozen.json",
            "dough_based_products_or_meals_not_ready_to_eat_savoury_shelf_stable.json",
            "dressings_or_dips_shelf_stable.json",
            "dried_breads_shelf_stable.json",
            "drinks.json",
            "drinks_energy_drinks.json",
            "drinks_flavoured_ready_to_drink.json",
            "drinks_juices_drinks_and_cordials.json",
            "drinks_powdered.json",
            "drinks_soft_drinks.json",
            "egg_based_products_or_meals_not_ready_to_eat_frozen.json",
            "eggs.json",
            "eggs_&_egg_substitutes.json",
            "eggs_or_eggs_substitutes.json",
            "eggs_products_or_substitutes.json",
            "energy_protein_&_muscle_recovery_drinks.json",
            "entrees_sides_&_small_meals.json",
            "extracts_or_salt_or_meat_tenderisers_shelf_stable.json",
            "fats_edible.json",
            "fatty_acid_supplements.json",
            "fish_&_seafood.json",
            "fish_prepared_or_processed.json",
            "fish_unprepared_or_unprocessed.json",
            "fish_–_prepared_or_processed.json",
            "fish_–_unprepared_or_unprocessed.json",
            "flavored_rice_dishes.json",
            "flavored_snack_crackers.json",
            "flour_cereal_or_pulse_shelf_stable.json",
            "flours_&_corn_meal.json",
            "food_or_beverage_or_tobacco_variety_packs.json",
            "foundational_foods.json",
            "french_fries_potatoes_&_onion_rings.json",
            "fresh_chicken_portions.json",
            "fresh_chicken_processed.json",
            "fresh_chicken_whole.json",
            "fresh_fruit_and_vegetables.json",
            "fresh_meat.json",
            "fresh_meat_poultry_and_seafood.json",
            "fresh_pasta.json",
            "frozen_appetizers_&_hors_doeuvres.json",
            "frozen_bacon_sausages_&_ribs.json",
            "frozen_bread_&_dough.json",
            "frozen_breakfast_sandwiches_biscuits_&_meals.json",
            "frozen_chicken_portions.json",
            "frozen_chicken_processed.json",
            "frozen_desserts.json",
            "frozen_dinners_&_entrees.json",
            "frozen_fish_&_seafood.json",
            "frozen_fish_or_seafood.json",
            "frozen_foods.json",
            "frozen_fruit.json",
            "frozen_fruit_&_fruit_juice_concentrates.json",
            "frozen_meals.json",
            "frozen_meat.json",
            "frozen_pancakes_waffles_french_toast_&_crepes.json",
            "frozen_patties_and_burgers.json",
            "frozen_pies_or_savouries.json",
            "frozen_potato.json",
            "frozen_poultry_chicken_&_turkey.json",
            "frozen_prepared_sides.json",
            "frozen_sausages_hotdogs_&_brats.json",
            "frozen_snack.json",
            "frozen_vegetables.json",
            "fruit.json",
            "fruit_&_vegetable_juice_nectars_&_fruit_drinks.json",
            "fruit_juice_not_ready_to_drink_frozen.json",
            "fruit_juice_ready_to_drink_shelf_stable.json",
            "fruit_or_nuts_or_seeds_combination.json",
            "fruit_or_nuts_or_seeds_mixes_prepared_or_processed_shelf_stable.json",
            "fruit_prepared_or_processed.json",
            "fruit_prepared_or_processed_frozen.json",
            "fruit_prepared_or_processed_shelf_stable.json",
            "fruits_unprepared_or_unprocessed_frozen.json",
            "fruits_unprepared_or_unprocessed_shelf_stable.json",
            "fruits_vegetables_&_produce.json",
            "gelatin_gels_pectins_&_desserts.json",
            "grain_based_products_or_meals.json",
            "grain_based_products_or_meals_not_ready_to_eat_savoury_frozen.json",
            "grain_based_products_or_meals_not_ready_to_eat_savoury_shelf_stable.json",
            "grains.json",
            "grains_or_cereal_not_ready_to_eat_shelf_stable.json",
            "grains_or_cereal_ready_to_eat_shelf_stable.json",
            "grains_or_flour.json",
            "granulated_brown_&_powdered_sugar.json",
            "gravy_mix.json",
            "green_supplements.json",
            "ham_or_cold_meats.json",
            "health_care.json",
            "health_supplements_and_vitamins.json",
            "herbal_supplements.json",
            "herbs_&_spices.json",
            "herbs_and_spices.json",
            "herbs_or_spices_or_extracts.json",
            "herbs_or_spices_shelf_stable.json",
            "home_decoration_&_supplies.json",
            "honey.json",
            "ice_cream_&_frozen_yogurt.json",
            "ice_cream_or_block_single.json",
            "ice_cream_or_ice_block_multi_pack.json",
            "ice_cream_or_ice_novelties_shelf_stable.json",
            "ice_cream_take_home.json",
            "iced_&_bottle_tea.json",
            "infant_formula.json",
            "jam_jelly_&_fruit_spreads.json",
            "ketchup_mustard_bbq_&_cheese_sauce.json",
            "liquid_water_enhancer.json",
            "lunch_snacks_&_combinations.json",
            "margarine_or_butter.json",
            "meal_replacement_supplements.json",
            "meat_or_poultry_or_other_animals_prepared_or_processed.json",
            "meat_or_poultry_or_other_animals_sausages_prepared_or_processed.json",
            "meat_or_poultry_or_other_animals_sausages_–_prepared_or_processed.json",
            "meat_or_poultry_or_other_animals_unprepared_or_unprocessed.json",
            "meat_or_poultry_or_other_animals_–_prepared_or_processed.json",
            "meat_or_poultry_or_other_animals_–_unprepared_or_unprocessed.json",
            "meat_substitutes.json",
            "mexican_dinner_mixes.json",
            "milk.json",
            "milk_additives.json",
            "milk_or_cream.json",
            "milk_or_cream_shelf_stable.json",
            "milk_or_milk_substitutes.json",
            "miscellanious.json",
            "mussels.json",
            "non_alcoholic_beverages_not_ready_to_drink.json",
            "non_alcoholic_beverages_ready_to_drink.json",
            "non_alcoholic_beverages_–_not_ready_to_drink.json",
            "non_alcoholic_beverages_–_ready_to_drink.json",
            "noodles.json",
            "nut_&_seed_butters.json",
            "nutritional_supplements.json",
            "nuts_or_seeds_prepared_or_processed.json",
            "nuts_or_seeds_prepared_or_processed_out_of_shell.json",
            "nuts_or_seeds_prepared_or_processed_shelf_stable.json",
            "nuts_or_seeds_unprepared_or_unprocessed_shelf_stable.json",
            "nuts_or_seeds_–_prepared_or_processed.json",
            "nuts_or_seeds_–_unprepared_or_unprocessed_shelf_stable.json",
            "oils_edible.json",
            "oils_edible_vegetable_or_plant_shelf_stable.json",
            "oriental_mexican_&_ethnic_sauces.json",
            "other_condiments.json",
            "other_cooking_sauces.json",
            "other_deli.json",
            "other_drinks.json",
            "other_frozen_desserts.json",
            "other_frozen_meats.json",
            "other_grains_&_seeds.json",
            "other_meats.json",
            "other_pet_food.json",
            "other_sauces_dipping_or_condiments_or_savoury_toppings_or_savoury_spreads_or_marinades_frozen.json",
            "other_sauces_dipping_or_condiments_or_savoury_toppings_or_savoury_spreads_or_marinades_shelf_stable.json",
            "other_snacks.json",
            "other_soups.json",
            "packaged_water.json",
            "pancakes_waffles_french_toast_&_crepes.json",
            "pasta.json",
            "pasta_by_shape_&_type.json",
            "pasta_dinners.json",
            "pasta_instant_meals.json",
            "pasta_or_noodles.json",
            "pasta_or_noodles_not_ready_to_eat_frozen.json",
            "pastries_or_pies_or_pizzas.json",
            "pastry.json",
            "pastry_shells_&_fillings.json",
            "pepperoni_salami_&_cold_cuts.json",
            "pickled_vegetables.json",
            "pickles_olives_peppers_&_relishes.json",
            "pickles_or_relishes_or_chutneys_or_olives.json",
            "pickles_relishes_and_vinegar.json",
            "pies_or_pastries_or_pizzas_or_quiches_savoury_frozen.json",
            "pies_or_pastries_sweet_frozen.json",
            "pies_or_pastries_sweet_shelf_stable.json",
            "pizza.json",
            "pizza_mixes_&_other_dry_dinners.json",
            "plant_based_milk.json",
            "plant_based_water.json",
            "popcorn_peanuts_seeds_&_related_snacks.json",
            "popcorn_shelf_stable.json",
            "potato_instant_meals.json",
            "poultry_chicken_&_turkey.json",
            "powdered_drinks.json",
            "pre_packaged_fruit_&_vegetables.json",
            "prepared_meals.json",
            "prepared_or_preserved_foods_variety_packs.json",
            "prepared_pasta_&_pizza_sauces.json",
            "prepared_soups.json",
            "prepared_subs_&_sandwiches.json",
            "prepared_wraps_and_burittos.json",
            "processed_cereal_products.json",
            "processed_cheese_&_cheese_novelties.json",
            "puddings_&_custards.json",
            "puddings_and_desserts.json",
            "ready_made_combination_meals.json",
            "ready_made_combination_meals_not_ready_to_eat_frozen.json",
            "ready_to_drink.json",
            "rice.json",
            "rice_&_grains.json",
            "s_or_o_fresh_fish_fillets_or_steaks.json",
            "salad_dressing_&_mayonnaise.json",
            "salad_dressings.json",
            "salads.json",
            "salami_or_cured_meat.json",
            "sandwiches_or_filled_rolls_or_wraps.json",
            "sandwiches_or_filled_rolls_or_wraps_frozen.json",
            "sauces.json",
            "sauces_cooking.json",
            "sauces_cooking_frozen.json",
            "sauces_cooking_shelf_stable.json",
            "sauces_or_spreads_or_dips_or_condiments.json",
            "sausages_hotdogs_&_brats.json",
            "sausages_or_smallgoods.json",
            "savoury_bakery_products.json",
            "seafood_miscellaneous.json",
            "seasoning_mixes_salts_marinades_&_tenderizers.json",
            "seasonings_or_preservatives_or_extracts_variety_packs.json",
            "shellfish_prepared_or_processed.json",
            "shellfish_unprepared_or_unprocessed.json",
            "skin_care_preparations.json",
            "smoked_fish.json",
            "snack_energy_&_granola_bars.json",
            "snack_foods_cereal_snacks.json",
            "snack_foods_chips.json",
            "snack_foods_corn_chips.json",
            "snack_foods_dried_fruit.json",
            "snack_foods_multi_packs.json",
            "snack_foods_nuts.json",
            "snack_foods_other.json",
            "snacks.json",
            "snacks_other.json",
            "snacks_variety_packs.json",
            "soda.json",
            "soups_prepared_shelf_stable.json",
            "specialty_formula_supplements.json",
            "sport_drinks.json",
            "sports_and_weight_management.json",
            "spreads.json",
            "stuffing.json",
            "sugar_and_flour.json",
            "sugar_candy_or_sugar_candy_substitutes_confectionery.json",
            "sugars_or_sugar_substitute_products.json",
            "sushi.json",
            "sweet_bakery_products.json",
            "sweet_spreads.json",
            "syrups_&_molasses.json",
            "taco_shells.json",
            "tea_bags.json",
            "tea_bags_loose_leaf_speciality.json",
            "tofu.json",
            "tomatoes.json",
            "turkey_unprepared_or_unprocessed.json",
            "vegetable_&_cooking_oils.json",
            "vegetable_and_lentil_mixes.json",
            "vegetable_based_products_or_meals.json",
            "vegetable_based_products_or_meals_not_ready_to_eat_frozen.json",
            "vegetable_based_products_or_meals_not_ready_to_eat_shelf_stable.json",
            "vegetables.json",
            "vegetables_prepared_or_processed.json",
            "vegetables_prepared_or_processed_frozen.json",
            "vegetables_prepared_or_processed_shelf_stable.json",
            "vegetables_unprepared_or_unprocessed_frozen.json",
            "vegetables_unprepared_or_unprocessed_shelf_stable.json",
            "vegetables_–_prepared_or_processed.json",
            "vegetables_–_unprepared_or_unprocessed_frozen.json",
            "vegetables_–_unprepared_or_unprocessed_shelf_stable.json",
            "vegetarian.json",
            "vegetarian_frozen_meats.json",
            "vitamins.json",
            "water.json",
            "weight_control.json",
            "wholesome_snacks.json",
            "wrapped_snacks_cereal.json",
            "wrapped_snacks_fruit_bars.json",
            "wrapped_snacks_muesli_bars.json",
            "wrapped_snacks_nut_bars.json",
            "yogurt.json",
            "yogurt_or_yogurt_substitutes.json",
            "yogurt_or_yogurt_substitutes_perishable.json",
            "yogurt_perishable.json"};

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

        // Inflate, define, and modify views
        View view = getLayoutInflater().inflate(R.layout.fragment_dialog_importer, container, false);

        TextView tvParagraph = view.findViewById(R.id.tv_paragraph);
        String text = "Warning! This is an experimental feature that may take a couple of hours to complete. Please make sure to let the process finalize to prevent errors in data.\n\nDo you want to download ~ 100 MB of data from the domain below?\n\n" + baseURL;
        tvParagraph.setText(text);

        // Set click listener to import foods from online source
        view.findViewById(R.id.b_cancel).setOnClickListener(v -> dismiss());

        // Set click listener to start a foreground service for online food download
        view.findViewById(R.id.b_confirm).setOnClickListener(v -> {
            Intent intent = new Intent(requireContext(), DownloadService.class);
            intent.putExtra("files", files);
            intent.putExtra("baseURL", baseURL);
            requireActivity().startService(intent);
            dismiss();
        });

        return view;
    }

    // Create method to set the window parameters
    @Override
    public void onResume() {
        super.onResume();
        ReusableMethods.setDialogWindowParameters(Objects.requireNonNull(getDialog()));
    }
}