name: CI test

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Check the code
        uses: actions/checkout@v2

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: report.htm
          path: app/build/reports/lint-results-debug.htm

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one line script
        run: echo Hello 1

      - name: Run many lines
        run: |
          echo Hello 2
          echo Hello 3