name: CI test

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one line script
        run: echo Hello 1

      - name: Run many lines
        run: |
          echo Hello 2
          echo Hello 3